import Link from 'next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import nav__img from '../public/img/nav.png'

const inter = Inter({ subsets: ['latin'] })



// const navMenu = document.getElementById('nav-menu')
// const navClose = document.getElementById('nav-close')

// if (navMenu) {
//   navMenu.addEventListener('click', () => {
//     navMenu.classList.add('show-menu')
//   })
// }

// if (navClose) {
//   navClose.addEventListener('click', () => {
//     navMenu.classList.remove('show-menu')
//   })
// }


export const metadata: Metadata = {
  title: 'Meadowbrook United Church',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="meadowbrook united church" content="meadowbrook united church website, that contaains information about the history of the church. I also give information to members pertaing the next church service, notices, calendar evens, etc."></meta>
      <meta name="muc" content="Meadowbrook united church."></meta>
      <body className={inter.className}>
        <header className="header">
          <Image src={nav__img} alt='nav__bg' className='header__bg'></Image>
          <div className="nav__heading">
            <div className="header__logo-group">
              <svg className="header__logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 66 66" >
                <path d="M26.4 66V52.8C26.4 51.0496 27.0954 49.3708 28.3331 48.1331C29.5708 46.8954 31.2496 46.2 33 46.2C34.7504 46.2 36.4292 46.8954 37.6669 48.1331C38.9046 49.3708 39.6 51.0496 39.6 52.8V66H52.8V33C52.7999 32.4306 52.6524 31.8709 52.372 31.3753C52.0915 30.8797 51.6876 30.4652 51.1995 30.1719L36.3 21.2322V13.2H42.9V6.6H36.3V0H29.7V6.6H23.1V13.2H29.7V21.2322L14.8005 30.1719C14.3124 30.4652 13.9085 30.8797 13.628 31.3753C13.3476 31.8709 13.2001 32.4306 13.2 33V66H26.4ZM3.3 66H9.9V39.2106L1.8249 43.2498C1.27635 43.5231 0.814929 43.944 0.492536 44.4652C0.170143 44.9863 -0.000430982 45.5872 8.17778e-07 46.2V62.7C8.17778e-07 63.5752 0.347678 64.4146 0.966548 65.0335C1.58542 65.6523 2.42479 66 3.3 66ZM64.1751 43.2465L56.1 39.2106V66H62.7C63.5752 66 64.4146 65.6523 65.0335 65.0335C65.6523 64.4146 66 63.5752 66 62.7V46.2C66 44.9493 65.2938 43.8075 64.1751 43.2465Z" fill="black" />
              </svg>
              <h1 className="header__text">Meadowbrook united church</h1>
            </div>
            <ul className="nav__items">
              <li className="nav__link"><Link href="./">Home</Link></li>
              <li className="nav__link"><Link href="./gallary">Gallary</Link></li>
              <li className="nav__link"><Link href="./about">About</Link></li>
              <li className="nav__link"><Link href="./notice">Notice</Link></li>
              <li className="nav__link"><Link href="./contact">Contact Us</Link></li>
              <li className="nav__link"><Link href="./donate">Donate</Link></li>
            </ul>
          </div>
        </header>
        <div className="nav__icon-group">
          <svg className='nav__icon-menu' id='nav-menu' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z" />
          </svg>
          <svg className='nav__icon-close' id='nav-close' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
            <path d="M376.6 84.5c11.3-13.6 9.5-33.8-4.1-45.1s-33.8-9.5-45.1 4.1L192 206 56.6 43.5C45.3 29.9 25.1 28.1 11.5 39.4S-3.9 70.9 7.4 84.5L150.3 256 7.4 427.5c-11.3 13.6-9.5 33.8 4.1 45.1s33.8 9.5 45.1-4.1L192 306 327.4 468.5c11.3 13.6 31.5 15.4 45.1 4.1s15.4-31.5 4.1-45.1L233.7 256 376.6 84.5z" />
          </svg>
        </div>
        {children}
        <footer className="footer__bg">
          <Link href='mailto:kahlil.j.richards@gmail.com?subject=Feedback from Meadowbrook website&body=I Like your website. I would like to connect on further business'>
            <h1 className="footer__text">Copyright 2024. by Kahlil Richards</h1>
          </Link>
        </footer></body>
    </html>
  )
}
